import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="style.css"></link>
        <link rel="shortcut icon" href="favicon.png" type="image/x-icon"/>
        <title>Facebook - login or sign up</title>
      </Head>
     <main>
      <div className=''> 

      </div>
     </main>
    </>
  )
}
